locations/urls.py
from django.urls import path
from locations.views import LocationListView, LocationCreateView, LocationUpdateView, LocationDeleteView, \
    LocationHistoryView, get_attributes_for_type, get_selected_attributes_for_location, get_values_for_attribute, \
    download_locations

urlpatterns = [
    path('locations/', LocationListView.as_view(), name='location_list'),
    path('locations/create/', LocationCreateView.as_view(), name='location_create'),
    path('locations/<int:pk>/edit/', LocationUpdateView.as_view(), name='location_edit'),
    path('locations/<int:pk>/delete/', LocationDeleteView.as_view(), name='location_delete'),
    path('locations/<int:pk>/history/', LocationHistoryView.as_view(), name='location_history'),
    #  JSON
    path('download-locations/', download_locations, name='download-locations'),
    #  Ajax
    path('type_of_place/<int:type_of_place_id>/attributes/', get_attributes_for_type, name='get_attributes_for_type'),
    path('attributes/<int:attribute_id>/values/', get_values_for_attribute, name='get_values_for_attribute'),
    path('locations/<int:location_id>/selected_attributes/', get_selected_attributes_for_location,
         name='get_selected_attributes_for_location'),
]

problematy/urls.py
from django.contrib import admin
from django.urls import path, include
from problematy.view import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authorization.urls")),
    path("", include("configuration.urls")),
    path("", include("locations.urls")),

    path("", DashboardView.as_view(), name="index"),
]

authorization/models/roles.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class Role(models.Model):
    name = models.CharField(_('role name'), max_length=255, unique=True)
    permissions = models.ManyToManyField('Permission', related_name='roles')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class PermissionChoices(models.TextChoices):
    EDIT_LOCATIONS = 'edit_locations', _('Edit Locations')
    DELETE_LOCATIONS = 'delete_locations', _('Delete Locations')
    ADD_LOCATIONS = 'add_locations', _('Add Locations')
    CHECK_LOCATIONS = 'check_locations', _('Check Locations')
    MANAGE_USERS = 'manage_users', _('Manage Users')
    CONFIGURATION_ROLES = 'configuration_roles', _('Configuration: Roles')
    CONFIGURATION_ATTRIBUTES_AND_VALUES = 'configuration_attributes_and_values', _('Configuration: Attributes & Values')
    CONFIGURATION_TYPE_OF_PLACES = 'configuration_type_of_places', _('Configuration: Types of Places')
    CONFIGURATION_GENERAL_SETTINGS = 'configuration_general_settings', _('Configuration: General Settings')


class Permission(models.Model):
    name = models.CharField(
        _('permission name'),
        max_length=255,
        unique=True,
        choices=PermissionChoices.choices
    )
    codename = models.CharField(
        _('permission codename'),
        max_length=100,
        unique=True,
        blank=True
    )

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = slugify(self.name)
        super(Permission, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

configuration/models/attribute.py
from django.db import models


class Attribute(models.Model):
    name = models.CharField(max_length=100)
    visible_in_categories = models.BooleanField(default=True)
    visible_in_visible_data = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_values_list(self):
        return [value.content for value in self.values.all()]

    def __str__(self):
        return self.name


class Value(models.Model):
    attribute = models.ForeignKey(Attribute, related_name='values', on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.content}"

templates/partials/base.html
{% load custom_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description">
    <meta content="coderthemes" name="author">

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- App css -->

    <link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

    <!-- icons -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />


    {% block css %}
    {% block extra_css %} {% endblock extra_css %}
    {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-color="light" data-layout-mode="default" data-layout-size="fluid"
    data-topbar-color="light" data-leftbar-position="fixed" data-leftbar-color="light" data-leftbar-size='default'
    data-sidebar-user='true'>


    <div id="wrapper">

        {% block topbar %}
        {% endblock topbar %}

        {% include "partials/left-sidebar.html" %}

        <div class="content-page">
            <div class="content">

                <div class="container-fluid">
                    {% block content %}
                    {% endblock content %}
                </div>

            </div>


        </div>

    </div>


    {% include "partials/vendor.html" %}

    {% block extra_js %} {% endblock extra_js %}


    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
    <script src="{% static 'js/pages/custom_select2.js' %}"></script>

</body>

</html>

templates/partials/footer.html
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> &copy; Adminto theme by <a href="">Coderthemes</a> 
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-sm-block">
                    <a href="javascript:void(0);">About Us</a>
                    <a href="javascript:void(0);">Help</a>
                    <a href="javascript:void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

templates/partials/head-css.html
{% load static %}
<!-- App css -->
<link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

<!-- icons -->
<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />

templates/partials/layout-horizontal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-mode="horizontal" data-layout-color="light" data-layout-size="fluid"
      data-topbar-color="dark" data-leftbar-position="fixed">


<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/topbar-dark.html" %}
    {% include "partials/horizontal-nav.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/layout-preloader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-color="light" data-layout-mode="default" data-layout-size="fluid"
      data-topbar-color="light" data-leftbar-position="fixed" data-leftbar-color="light" data-leftbar-size='default'
      data-sidebar-user='true'>

        <!-- Pre-loader -->
        <div id="preloader">
            <div id="status">
                <div class="spinner">Loading...</div>
            </div>
        </div>
        <!-- End Preloader-->

<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/left-sidebar.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/layout-vertical.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-color="light" data-layout-mode="default" data-layout-size="fluid"
      data-topbar-color="light" data-leftbar-position="fixed" data-leftbar-color="light" data-leftbar-size='default'
      data-sidebar-user='true'>

<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/left-sidebar.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

templates/partials/left-sidebar.html
{% load custom_tags %}
{% load static %}
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

    <div class="h-100" data-simplebar>
        <div id="sidebar-menu">
            <ul id="side-menu">
                {% if request.user.is_superuser or can_add_locations or can_edit_locations or can_delete_locations or can_check_locations %}
                    <li>
                        <a href="{% url 'location_list' %}">
                            <i class="mdi mdi-tag-multiple"></i> Locations
                        </a>
                    </li>
                {% endif %}
                {% if request.user.is_superuser or can_manage_users %}
                    <li>
                        <a href="{% url 'user_list' %}">
                            <i class="mdi mdi-account-multiple-outline"></i> User Management
                        </a>
                    </li>
                {% endif %}
                {% if request.user.is_superuser or can_configurate_roles or can_configurate_attributes_and_values or can_configurate_type_of_places or can_configurate_general_settings %}
                    <li>
                        <a href="#sidebarComponents" data-bs-toggle="collapse">
                            <i class="mdi mdi-briefcase-outline"></i>
                            <span> Configuration </span>
                            <span class="menu-arrow"></span>
                        </a>
                        <div class="collapse" id="sidebarComponents">
                            <ul class="nav-second-level">
                                {% if request.user.is_superuser or can_configurate_roles %}
                                    <li>
                                        <a href="{% url 'role_list' %}">
                                            <i class="mdi mdi-key"></i> User Roles
                                        </a>
                                    </li>
                                {% endif %}
                                {% if request.user.is_superuser or can_configurate_attributes_and_values %}
                                    <li>
                                        <a href="{% url 'attribute_list' %}">
                                            <i class="mdi mdi-tag-multiple"></i> Attributes & Values
                                        </a>
                                    </li>
                                {% endif %}
                                {% if request.user.is_superuser or can_configurate_type_of_places %}
                                    <li>
                                        <a href="{% url 'type_of_place_list' %}">
                                            <i class="mdi mdi-map-marker-outline"></i> Types of Places
                                        </a>
                                    </li>
                                {% endif %}
                                {% if request.user.is_superuser or can_configurate_general_settings %}
                                    <li>
                                        <a href="{% url 'general_settings' %}">
                                            <i class="mdi mdi-cog-outline"></i> General settings
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- End Sidebar -->

        <div class="clearfix"></div>

    </div>
    <!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

templates/partials/title-meta.html
{% load static %}
<meta charset="utf-8" />
<title>{{title}} | Adminto - Responsive Admin Dashboard Template</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

templates/partials/topbar.html
{% load static %}
<!-- Topbar Start -->
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-end mb-0">

        <li class="dropdown notification-list topbar-dropdown">
            <a class="nav-link dropdown-toggle nav-user me-0 waves-effect waves-light" data-bs-toggle="dropdown"
               href="#" role="button" aria-haspopup="false" aria-expanded="false">
                <img src="https://ui-avatars.com/api/?name={{ request.user.get_full_name }}" alt="user-image"
                     class="rounded-circle">


                <span class="pro-user-name ms-1">
                        {{ request.user.get_full_name }} <i class="mdi mdi-chevron-down"></i>
                    </span>
            </a>
            <div class="dropdown-menu dropdown-menu-end profile-dropdown ">
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="dropdown-item notify-item">
                        <i class="fe-log-out"></i>
                        <span>Logout</span>
                    </button>
                </form>
            </div>
        </li>
    </ul>
    <!-- LOGO -->
    <div class="logo-box">
        <a href="{% url 'index' %}" class="logo logo-light text-center">
                <span class="logo-sm">
                    <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                </span>
            <span class="logo-lg">
                    <img src="{% static 'images/logo-light.png' %}" alt="" height="16">
                </span>
        </a>
        <a href="{% url 'index' %}" class="logo logo-dark text-center">
                <span class="logo-sm">
                    <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
                </span>
            <span class="logo-lg">
                    <img src="{% static 'images/logo-dark.png' %}" alt="" height="16">
                </span>
        </a>
    </div>

    <ul class="list-unstyled topnav-menu topnav-menu-left mb-0">
        <li>
            <button class="button-menu-mobile disable-btn waves-effect">
                <i class="fe-menu"></i>
            </button>
        </li>
    </ul>

    <div class="clearfix"></div>

</div>
<!-- end Topbar -->

templates/partials/vendor.html
{% load static %}
<!-- Vendor -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'libs/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'libs/jquery.counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'libs/feather-icons/feather.min.js' %}"></script>