locations/urls.py
from django.urls import path
from locations.views import LocationListView, LocationCreateView, LocationUpdateView, LocationDeleteView, \
    LocationHistoryView, get_attributes_for_type, get_selected_attributes_for_location, get_values_for_attribute, \
    download_locations

urlpatterns = [
    path('locations/', LocationListView.as_view(), name='location_list'),
    path('locations/create/', LocationCreateView.as_view(), name='location_create'),
    path('locations/<int:pk>/edit/', LocationUpdateView.as_view(), name='location_edit'),
    path('locations/<int:pk>/delete/', LocationDeleteView.as_view(), name='location_delete'),
    path('locations/<int:pk>/history/', LocationHistoryView.as_view(), name='location_history'),
    #  JSON
    path('download-locations/', download_locations, name='download-locations'),
    #  Ajax
    path('type_of_place/<int:type_of_place_id>/attributes/', get_attributes_for_type, name='get_attributes_for_type'),
    path('attributes/<int:attribute_id>/values/', get_values_for_attribute, name='get_values_for_attribute'),
    path('locations/<int:location_id>/selected_attributes/', get_selected_attributes_for_location,
         name='get_selected_attributes_for_location'),
]

problematy/urls.py
from django.contrib import admin
from django.urls import path, include
from problematy.view import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authorization.urls")),
    path("", include("configuration.urls")),
    path("", include("locations.urls")),

    path("", DashboardView.as_view(), name="index"),
]

locations/models/location.py
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _
from model_utils import FieldTracker

from configuration.models import TypeOfPlace, Attribute, TypeOfPlaceAttribute, Value
from authorization.models import CustomUser


class Location(models.Model):
    STATUS_CHOICES = [
        ('visible', _('Visible')),
        ('hidden', _('Hidden')),
    ]

    CHECK_STATUS_CHOICES = [
        ('exists', _('Exists')),
        ('does_not_exist', _('Does not exist')),
        ('check', _('To Check')),
    ]

    name = models.CharField(_('Name'), max_length=255, blank=False)
    type_of_place = models.ForeignKey(TypeOfPlace, on_delete=models.SET_NULL, null=True, blank=False)
    status = models.CharField(_('Status'), max_length=15, choices=STATUS_CHOICES, default='visible')
    check_status = models.CharField(_('Check Status'), max_length=15, choices=CHECK_STATUS_CHOICES, default='check')
    latitude = models.DecimalField(_('Latitude'), max_digits=21, decimal_places=18, null=True, blank=True)
    longitude = models.DecimalField(_('Longitude'), max_digits=21, decimal_places=18, null=True, blank=True)
    image = models.ImageField(_('Image'), upload_to='locations/', null=True, blank=True)
    last_checked = models.DateField(_('Last Checked'), null=True, blank=True)
    website = models.URLField(max_length=255, blank=True, null=True)
    comments = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tracker = FieldTracker()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        changes = self.tracker.changed()
        super().save(*args, **kwargs)

    def get_coordinates(self):
        return f"[{self.latitude}, {self.longitude}]"

    def clean(self):
        super().clean()  # Always call the base class clean
        if not self.name:
            raise ValidationError({'name': _('This field is required.')})
        if not self.type_of_place:
            raise ValidationError({'type_of_place': _('This field is required.')})
        if self.latitude is not None and (self.latitude < -90 or self.latitude > 90):
            raise ValidationError({'latitude': _('Latitude must be between -90 and 90.')})
        if self.longitude is not None and (self.longitude < -180 or self.longitude > 180):
            raise ValidationError({'longitude': _('Longitude must be between -180 and 180.')})


class LocationAttribute(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='location_attributes')
    type_of_place_attribute = models.ForeignKey(TypeOfPlaceAttribute, on_delete=models.CASCADE)
    selected_values = models.ManyToManyField(Value)

    tracker = FieldTracker()

    def __str__(self):
        return f"{self.location.name} - {self.type_of_place_attribute.attribute.name}"

    def get_selected_values_display(self):
        return ', '.join([value.content for value in self.selected_values.all()])


class LocationChangeLog(models.Model):
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    change_description = models.TextField()
    change_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.change_description} at {self.change_date}"

locations/views/ajax_view.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from configuration.models import TypeOfPlace, Value
from locations.models import Location


def get_attributes_for_type(request, type_of_place_id):
    type_of_place = get_object_or_404(TypeOfPlace, pk=type_of_place_id)
    attributes = type_of_place.attributes.values('id', 'name')
    return JsonResponse(list(attributes), safe=False)


def get_values_for_attribute(request, attribute_id):
    values = Value.objects.filter(attribute_id=attribute_id)
    values_data = list(values.values('id', 'content'))
    return JsonResponse(values_data, safe=False)


def get_selected_attributes_for_location(request, location_id):
    location = get_object_or_404(Location, pk=location_id)
    selected_attributes = location.location_attributes.all()

    attributes_data = [
        {
            'attribute_id': loc_attr.type_of_place_attribute.attribute.id,
            'type_of_place_id': loc_attr.type_of_place_attribute.type_of_place.id,
            'selected_values': list(loc_attr.selected_values.values_list('id', flat=True))
        }
        for loc_attr in selected_attributes
    ]
    return JsonResponse(attributes_data, safe=False)

locations/views/json_data_viev.py
from django.http import JsonResponse

from gcs_config import download_blob
from problematy import settings


def download_locations(request):
    data = download_blob(settings.LOCATIONS_BLOB_FILEPATH)
    return JsonResponse(data, safe=False)

locations/views/location_view.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from configuration.models import TypeOfPlaceAttribute, Value
from locations.forms import LocationCreateForm, LocationEditForm
from locations.forms import LocationFilterForm
from locations.models import Location, LocationAttribute, LocationChangeLog
from locations.utils import log_attribute_changes, update_map_json
from problematy.utils import get_user_permissions, PermissionMixin


class LocationListView(PermissionMixin, LoginRequiredMixin, ListView):
    model = Location
    template_name = 'locations/location_list.html'
    context_object_name = 'locations'
    paginate_by = 25

    def has_permission(self):
        required_permissions = {'can_add_locations', 'can_edit_locations', 'can_delete_locations',
                                'can_check_locations'}
        return any(self.user_perms.get(perm, False) for perm in required_permissions)

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-updated_at', '-created_at')
        filter_form = LocationFilterForm(self.request.GET)

        if filter_form.is_valid():
            search = filter_form.cleaned_data.get('search')
            status = filter_form.cleaned_data.get('status')
            check_status = filter_form.cleaned_data.get('check_status')
            type_of_place = filter_form.cleaned_data.get('type_of_place')
            attribute = filter_form.cleaned_data.get('attribute')
            attribute_values = filter_form.cleaned_data.get('attribute_value')

            if search:
                queryset = queryset.filter(name__icontains=search)
            if status:
                queryset = queryset.filter(status=status)
            if check_status:
                queryset = queryset.filter(check_status=check_status)
            if type_of_place:
                queryset = queryset.filter(type_of_place=type_of_place)
            if attribute:
                queryset = queryset.filter(location_attributes__type_of_place_attribute__attribute=attribute)
            if attribute_values:
                queryset = queryset.filter(location_attributes__selected_values__in=attribute_values).distinct()

        return queryset

    def get_filter_form(self):
        return LocationFilterForm(self.request.GET or None)

    def filter_by_attribute_value(self, queryset, attribute, attribute_value):
        return queryset

    def get_context_data(self, **kwargs):
        context = super(LocationListView, self).get_context_data(**kwargs)
        queryset = self.get_queryset()
        paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, self.paginate_by)
        page_number = page.number
        per_page = paginator.per_page
        start_index = (page_number - 1) * per_page + 1

        selected_attribute_values = self.request.GET.getlist('attribute_value')
        context['attribute_value_list_json'] = json.dumps(selected_attribute_values, cls=DjangoJSONEncoder)
        context.update({
            'filter_form': self.get_filter_form(),
            'paginator': paginator,
            'page_obj': page,
            'is_paginated': is_paginated,
            'page': page,  # Duplicate for easy access in templates
            'queryset': queryset,
            'start_index': start_index
        })
        context.update(get_user_permissions(self.request.user))  # Добавление прав пользователя
        return context


class LocationCreateView(PermissionMixin, LoginRequiredMixin, CreateView):
    model = Location
    form_class = LocationCreateForm
    template_name = 'locations/location_create.html'
    success_url = reverse_lazy('location_list')

    def has_permission(self):
        required_permissions = {'can_add_locations'}
        return any(self.user_perms.get(perm, False) for perm in required_permissions)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update(get_user_permissions(self.request.user))
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        changes = self.object.tracker.changed()
        self.object.save()

        type_of_place = form.cleaned_data.get('type_of_place')

        posted_attribute_ids = {}
        for key in self.request.POST:
            if key.startswith('attribute_values_'):
                attr_id = key.split('_')[-1]
                try:
                    attr_id = int(attr_id)
                    value_ids = self.request.POST.getlist(f'selected_values_{attr_id}[]')
                    posted_attribute_ids[attr_id] = value_ids
                except ValueError:
                    continue

        if type_of_place:
            for key, values in self.request.POST.items():
                if key.startswith('attribute_values_'):
                    attribute_id = key.split('_')[-1]
                    try:
                        attribute_id = int(attribute_id)
                        value_ids = self.request.POST.getlist(f'selected_values_{attribute_id}[]')
                        type_place_attribute = TypeOfPlaceAttribute.objects.get(attribute_id=attribute_id,
                                                                                type_of_place=type_of_place)
                        loc_attr = LocationAttribute.objects.get_or_create(
                            location=self.object,
                            type_of_place_attribute=type_place_attribute
                        )[0]
                        loc_attr.selected_values.set(Value.objects.filter(id__in=value_ids))
                    except (ValueError, TypeOfPlaceAttribute.DoesNotExist, AttributeError):
                        continue

        log_attribute_changes(
            location=self.object,
            original_attr_values={},
            posted_attribute_ids=posted_attribute_ids,
            user=self.request.user,
            changes=changes,
            is_new=True
        )
        update_map_json()
        return super(LocationCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(LocationCreateView, self).get_form_kwargs()
        if self.request.method == 'POST':
            kwargs['type_of_place_id'] = self.request.POST.get('type_of_place', None)
        return kwargs


class LocationUpdateView(PermissionMixin, LoginRequiredMixin, UpdateView):
    model = Location
    form_class = LocationEditForm
    template_name = 'locations/location_edit.html'
    success_url = reverse_lazy('location_list')

    def has_permission(self):
        required_permissions = {'can_edit_locations'}
        return any(self.user_perms.get(perm, False) for perm in required_permissions)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.type_of_place:
            selected_attributes = LocationAttribute.objects.filter(location=self.object)
            # Создаем словарь для JS {attribute_id: [selected_value_ids]}
            existing_attributes = {
                attr.type_of_place_attribute.attribute.id: list(attr.selected_values.values_list('id', flat=True))
                for attr in selected_attributes
            }
            context['existingAttributes'] = existing_attributes
            context['selectedValues'] = {
                attr.id: [val.id for val in attr.selected_values.all()]
                for attr in selected_attributes
            }
        context.update(get_user_permissions(self.request.user))
        return context

    def form_valid(self, form):
        original_attr_values = {
            attr.type_of_place_attribute.attribute.id: list(set(attr.selected_values.values_list('id', flat=True)))
            for attr in LocationAttribute.objects.filter(location=self.object).prefetch_related('selected_values')
        }
        changes = self.object.tracker.changed()
        response = super().form_valid(form)
        type_of_place_id = form.cleaned_data.get('type_of_place').id if form.cleaned_data.get('type_of_place') else None

        if type_of_place_id:
            possible_attributes = TypeOfPlaceAttribute.objects.filter(type_of_place_id=type_of_place_id)
            attribute_ids = set(possible_attributes.values_list('attribute__id', flat=True))

            posted_attribute_ids = {}
            for key in self.request.POST.keys():
                if key.startswith('attribute_values_'):
                    attr_name = key[len('attribute_values_'):]
                    attr_id = self.request.POST[key]  # ID атрибута
                    if attr_id.isdigit() and int(attr_id) in attribute_ids:
                        value_ids = list(map(int, self.request.POST.getlist(f'selected_values_{attr_id}[]')))
                        posted_attribute_ids[int(attr_id)] = value_ids

            existing_attributes = LocationAttribute.objects.filter(location=self.object)

            # Удаляем атрибуты, которые не были включены в запрос
            attribute_ids_in_request = set(posted_attribute_ids.keys())
            attributes_to_remove = existing_attributes.exclude(
                type_of_place_attribute__attribute_id__in=attribute_ids_in_request)
            attributes_to_remove.delete()

            for attr_id, value_ids in posted_attribute_ids.items():
                attribute = TypeOfPlaceAttribute.objects.get(attribute_id=attr_id, type_of_place_id=type_of_place_id)
                loc_attr, created = LocationAttribute.objects.update_or_create(
                    location=self.object,
                    type_of_place_attribute=attribute,
                    defaults={}
                )

templates/locations/location_history.html
{% extends "partials/base.html" %}

{% block title %}Location History{% endblock %}

{% block topbar %}
    {% include "partials/topbar.html" with pagetitle="Location History" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title">Location Changes History</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-centered mb-0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th class="text-nowrap">Change Description</th>
                                <th class="text-nowrap">Changed By</th>
                                <th class="text-nowrap">Change Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for log in history %}
                                <tr>
                                    <td>{{ forloop.counter0|add:start_index }}</td>
                                    <td>{{ log.change_description|safe }}</td>
                                    <td>{{ log.user.get_full_name }}</td>
                                    <td>{{ log.change_date|date:"Y-m-d H:i" }}</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="4" class="text-center">No history records found</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    <br>
                        <!-- Pagination -->
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if page.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.previous_page_number }}">Previous</a>
                                    </li>
                                {% endif %}
                                {% for num in page.paginator.page_range %}
                                    {% if page.number == num %}
                                        <li class="page-item active"><a class="page-link"
                                                                        href="?page={{ num }}">{{ num }}</a></li>
                                    {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
                                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.next_page_number }}">Next</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.paginator.num_pages }}">Last
                                        &raquo;</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/locations/location_list.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}Locations Management{% endblock %}

{% block extra_css %}

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet"/>

{% endblock %}

{% block topbar %}
    {% include "partials/topbar.html" with pagetitle="Locations Management" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title">Locations Management</h4>
                    <button onclick="window.location.href='{% url 'download-locations' %}'" class="btn btn-primary">
                        Download Locations JSON
                    </button>

                    {% if request.user.is_superuser or can_add_locations %}
                        <a href="{% url 'location_create' %}" class="btn btn-success">Add Location</a>
                    {% endif %}
                </div>
                <div class="card-body">
                    <!-- Filter Form -->
                    <form method="get" class="mb-4">
                        <div class="row align-items-end">
                            <!-- Поиск должен занимать всю строку на мобильных устройствах и 100% ширины на всех экранах -->
                            <div class="col-12 mb-3">
                                <label class="form-label" for="{{ filter_form.search.id_for_label }}">Search</label>
                                {{ filter_form.search }}
                            </div>
                        </div>
                        <div class="row align-items-end">
                            <!-- Эти элементы занимают 3 колонки на средних и более крупных экранах, и всю ширину на мобильных -->
                            <div class="col-12 col-md-4 mb-3">
                                <label class="form-label" for="{{ filter_form.status.id_for_label }}">Status</label>
                                {{ filter_form.status }}
                            </div>
                            <div class="col-12 col-md-4 mb-3">
                                <label class="form-label" for="{{ filter_form.check_status.id_for_label }}">Check
                                    Status</label>
                                {{ filter_form.check_status }}
                            </div>
                            <div class="col-12 col-md-4 mb-3">
                                <label class="form-label" for="{{ filter_form.type_of_place.id_for_label }}">Type of
                                    Place</label>
                                {{ filter_form.type_of_place }}
                            </div>
                        </div>
                        <div class="row align-items-end">
                            <!-- Поля атрибутов занимают 6 колонок на средних и более крупных экранах, и всю ширину на мобильных -->
                            <div class="col-12 col-md-6 mb-3">
                                <label class="form-label"
                                       for="{{ filter_form.attribute.id_for_label }}">Attribute</label>
                                {{ filter_form.attribute }}
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <label class="form-label" for="{{ filter_form.attribute_value.id_for_label }}">Attribute
                                    Value</label>
                                {{ filter_form.attribute_value }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 d-flex justify-content-end">
                                <button type="submit" class="btn btn-primary me-2">Search</button>
                                <a href="{% url 'location_list' %}" class="btn btn-outline-secondary">Reset</a>
                            </div>
                        </div>
                    </form>
                    <div class="table-responsive">
                        <table class="table table-centered mb-0" id="btn-editable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th class="text-nowrap">Type of Place</th>
                                <th>Status</th>
                                <th class="text-nowrap">Check Status</th>
                                <th>
                                    <div class="d-flex align-items-center justify-content-center gap-2">
                                        Actions
                                    </div>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for location in page %}
                                <tr data-location-id="{{ location.id }}">
                                    <td>{{ forloop.counter0|add:start_index }}</td>
                                    <td>{{ location.name }}</td>
                                    <td>
                                        {% if location.type_of_place %}
                                            {{ location.type_of_place.name }}
                                        {% else %}
                                            N/A
                                        {% endif %}
                                    </td>
                                    <td>{{ location.get_status_display }}</td>
                                    <td>{{ location.get_check_status_display }}</td>
                                    <td>
                                        <div class="d-flex align-items-center justify-content-center gap-2">
                                            {% if request.user.is_superuser or can_edit_locations %}
                                                <a href="{% url 'location_edit' location.id %}"
                                                   class="btn btn-sm btn-primary">Edit</a>
                                            {% endif %}
                                            {% if request.user.is_superuser or can_delete_locations %}
                                                <button class="btn btn-sm btn-danger delete-location-button"
                                                        data-location-id="{{ location.id }}">Delete
                                                </button>
                                            {% endif %}
                                            <a href="{% url 'location_history' location.id %}"
                                               class="btn btn-sm btn-primary">History</a>
                                        </div>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="6" class="text-center">No search results</td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        </table>
                        <br>
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if page.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.previous_page_number }}">Previous</a>
                                    </li>
                                {% endif %}
                                {% for num in page.paginator.page_range %}
                                    {% if page.number == num %}
                                        <li class="page-item active"><a class="page-link"
                                                                        href="?page={{ num }}">{{ num }}</a></li>
                                    {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
                                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.next_page_number }}">Next</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.paginator.num_pages }}">Last
                                        &raquo;</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/pages/location_list.init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
{% endblock %}