authorization/urls.py
from django.urls import path

from authorization.views import RoleListView, RoleCreateView, RoleEditView, RoleDeleteView, \
    UsersListView, UserCreateView, UserEditView, UserDeleteView, \
    LoginView, CustomLogoutView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    # User
    path("user/list", UsersListView.as_view(), name="user_list"),
    path('user/create', UserCreateView.as_view(), name='create_user'),
    path("user/edit/<int:pk>/", UserEditView.as_view(), name="user_edit"),
    path("user/delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
    # Role
    path("roles/list/", RoleListView.as_view(), name='role_list'),
    path('roles/create/', RoleCreateView.as_view(), name='create_role'),
    path('roles/edit/<int:role_id>/', RoleEditView.as_view(), name='edit_role'),
    path('roles/delete/<int:pk>/', RoleDeleteView.as_view(), name='role_delete'),
]

locations/urls.py
from django.urls import path
from locations.views import LocationListView, LocationCreateView, LocationUpdateView, LocationDeleteView, \
    LocationHistoryView, get_attributes_for_type, get_selected_attributes_for_location, get_values_for_attribute, \
    download_locations

urlpatterns = [
    path('locations/', LocationListView.as_view(), name='location_list'),
    path('locations/create/', LocationCreateView.as_view(), name='location_create'),
    path('locations/<int:pk>/edit/', LocationUpdateView.as_view(), name='location_edit'),
    path('locations/<int:pk>/delete/', LocationDeleteView.as_view(), name='location_delete'),
    path('locations/<int:pk>/history/', LocationHistoryView.as_view(), name='location_history'),
    #  JSON
    path('download-locations/', download_locations, name='download-locations'),
    #  Ajax
    path('type_of_place/<int:type_of_place_id>/attributes/', get_attributes_for_type, name='get_attributes_for_type'),
    path('attributes/<int:attribute_id>/values/', get_values_for_attribute, name='get_values_for_attribute'),
    path('locations/<int:location_id>/selected_attributes/', get_selected_attributes_for_location,
         name='get_selected_attributes_for_location'),
]

problematy/urls.py
from django.contrib import admin
from django.urls import path, include
from problematy.view import DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authorization.urls")),
    path("", include("configuration.urls")),
    path("", include("locations.urls")),

    path("", DashboardView.as_view(), name="index"),
]

authorization/models/roles.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class Role(models.Model):
    name = models.CharField(_('role name'), max_length=255, unique=True)
    permissions = models.ManyToManyField('Permission', related_name='roles')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class PermissionChoices(models.TextChoices):
    EDIT_LOCATIONS = 'edit_locations', _('Edit Locations')
    DELETE_LOCATIONS = 'delete_locations', _('Delete Locations')
    ADD_LOCATIONS = 'add_locations', _('Add Locations')
    CHECK_LOCATIONS = 'check_locations', _('Check Locations')
    MANAGE_USERS = 'manage_users', _('Manage Users')
    CONFIGURATION_ROLES = 'configuration_roles', _('Configuration: Roles')
    CONFIGURATION_ATTRIBUTES_AND_VALUES = 'configuration_attributes_and_values', _('Configuration: Attributes & Values')
    CONFIGURATION_TYPE_OF_PLACES = 'configuration_type_of_places', _('Configuration: Types of Places')
    CONFIGURATION_GENERAL_SETTINGS = 'configuration_general_settings', _('Configuration: General Settings')


class Permission(models.Model):
    name = models.CharField(
        _('permission name'),
        max_length=255,
        unique=True,
        choices=PermissionChoices.choices
    )
    codename = models.CharField(
        _('permission codename'),
        max_length=100,
        unique=True,
        blank=True
    )

    def save(self, *args, **kwargs):
        if not self.codename:
            self.codename = slugify(self.name)
        super(Permission, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

authorization/forms/auth_form.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(label=_("Email"), widget=forms.TextInput(attrs={'autofocus': True}))

    def clean(self):
        email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, username=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

authorization/forms/role_form.py
from django import forms

from authorization.models import Role, PermissionChoices, Permission


class RoleForm(forms.ModelForm):
    permissions = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Role
        fields = ['name', 'permissions']

    def __init__(self, *args, **kwargs):
        super(RoleForm, self).__init__(*args, **kwargs)
        self.fields['permissions'].widget.attrs.update({'class': 'form-check-input'})

authorization/forms/user_edit_form.py
from django import forms
from django.contrib.auth.forms import UserChangeForm

from authorization.models import CustomUser


class EditUserForm(UserChangeForm):
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput,
        required=False  # Сделаем поле необязательным
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        required=False  # Сделаем поле необязательным
    )

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'role']
        widgets = {
            'email': forms.EmailInput(attrs={'readonly': 'readonly'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 or password2:  # Если есть хоть одно поле не пустое
            if password1 != password2:
                raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password1")
        if password:  # Теперь меняем пароль только если оба поля совпадают
            user.set_password(password)
        if commit:
            user.save()
        return user

authorization/views/login_view.py
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth import authenticate, login
from django.contrib import messages

from authorization.forms import CustomAuthenticationForm


class LoginView(View):
    authentication_form = CustomAuthenticationForm
    template_name = "authorization/login.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.error(request, "Invalid email or password.")
            return render(request, self.template_name)

authorization/views/logout_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy


class CustomLogoutView(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('login')

authorization/views/roles_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from authorization.forms import RoleForm
from authorization.models import Role, Permission
from problematy.utils import get_user_permissions, PermissionMixin


class RoleListView(PermissionMixin, LoginRequiredMixin, ListView):
    model = Role
    context_object_name = 'roles'
    template_name = 'authorization/roles_list.html'
    paginate_by = 25

    def has_permission(self):
        return self.user_perms.get('can_configurate_roles', False)

    def get_queryset(self):
        queryset = super(RoleListView, self).get_queryset()
        return queryset.order_by('-updated_at', '-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RoleListView, self).get_context_data(**kwargs)
        paginator, page, queryset, is_paginated = self.paginate_queryset(self.get_queryset(), self.paginate_by)

        page_number = context.get('page_obj').number
        per_page = context.get('paginator').per_page
        start_index = (page_number - 1) * per_page + 1

        context['paginator'] = paginator
        context['page'] = page
        context['queryset'] = queryset
        context['is_paginated'] = is_paginated
        context['start_index'] = start_index
        context.update(get_user_permissions(self.request.user))
        return context


class RoleCreateView(PermissionMixin, LoginRequiredMixin, View):
    template_name = "authorization/create_role.html"

    def has_permission(self):
        return self.user_perms.get('can_configurate_roles', False)

    def get(self, request, *args, **kwargs):
        form = RoleForm()
        permissions = Permission.objects.all()
        context = {
            'form': form,
            'permissions': permissions,
        }
        context.update(get_user_permissions(self.request.user))
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RoleForm(request.POST)
        if form.is_valid():
            role = form.save(commit=False)
            role.save()
            form.save_m2m()
            return redirect('role_list')
        else:
            return render(request, self.template_name, {'form': form})


class RoleEditView(PermissionMixin, LoginRequiredMixin, UpdateView):
    model = Role
    form_class = RoleForm
    template_name = 'authorization/edit_role.html'
    context_object_name = 'role'
    pk_url_kwarg = 'role_id'

    def has_permission(self):
        return self.user_perms.get('can_configurate_roles', False)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(get_user_permissions(self.request.user))
        return context

    def get_success_url(self):
        return reverse('role_list')


class RoleDeleteView(PermissionMixin, LoginRequiredMixin, View):
    def has_permission(self):
        return self.user_perms.get('can_configurate_roles', False)

    def post(self, request, *args, **kwargs):
        if not get_user_permissions(self.request.user).get("can_configurate_roles") and not self.request.user.is_superuser:
            return redirect('user_list')
        role_id = request.POST.get('id')
        role = get_object_or_404(Role, pk=role_id)
        role.delete()
        return redirect('role_list')

authorization/views/user_view.py
import re

from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from authorization.forms.user_edit_form import EditUserForm
from authorization.models import CustomUser, Role
from problematy.utils import get_user_permissions, PermissionMixin


class UsersListView(PermissionMixin, LoginRequiredMixin, View):
    model = CustomUser
    template_name = "authorization/user_list.html"
    paginate_by = 25

    def has_permission(self):
        return self.user_perms.get('can_manage_users', False)

    def get(self, request, *args, **kwargs):
        user_list = CustomUser.objects.all().order_by('-is_superuser', '-updated_at', '-date_joined', '-created_at')
        paginator = Paginator(user_list, self.paginate_by)

        page = request.GET.get('page', 1)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)

        start_index = (users.number - 1) * paginator.per_page + 1

        context = {
            'users': users,
            'start_index': start_index,
        }
        context.update(get_user_permissions(self.request.user))
        return render(request, self.template_name, context)


class UserCreateView(PermissionMixin, LoginRequiredMixin, View):
    template_name = 'authorization/create_user.html'
    raise_exception = True

    def has_permission(self):
        return self.user_perms.get('can_manage_users', False)

    def get(self, request, *args, **kwargs):
        roles = Role.objects.all()
        context = {
            'roles': roles,
        }
        context.update(get_user_permissions(self.request.user))
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        role_id = request.POST.get('role')
        password = request.POST.get('password1')
        password_confirmation = request.POST.get('password2')
        roles = Role.objects.all()

        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            messages.error(request, "Invalid email format.")
            return render(request, self.template_name, {'roles': roles})

        if password != password_confirmation:
            messages.error(request, "Passwords do not match.")
            return render(request, self.template_name, {'roles': roles})

        try:
            if CustomUser.objects.filter(email=email).exists():
                messages.error(request, "Email already exists.")
                return render(request, self.template_name, {'roles': roles})

            role = Role.objects.get(id=role_id)
            user = CustomUser.objects.create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                role=role,
                password=make_password(password),
            )

            user.save()
            return redirect('user_list')
        except ValidationError as e:
            messages.error(request, "Error creating user: " + str(e))
            return render(request, self.template_name, {'roles': roles})


class UserEditView(PermissionMixin, LoginRequiredMixin, View):

    def has_permission(self):
        return self.user_perms.get('can_manage_users', False)

    def get(self, request, pk):
        user = get_object_or_404(CustomUser, pk=pk)
        form = EditUserForm(instance=user)
        roles = Role.objects.all()
        context = {
            'form': form,
            'roles': roles,
            'user': user
        }
        context.update(get_user_permissions(self.request.user))
        return render(request, 'authorization/edit_user.html', context)

    def post(self, request, pk):
        user = get_object_or_404(CustomUser, pk=pk)
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user_list')
        else:
            messages.error(request, form.errors)  # Добавляем сообщение об ошибке в интерфейс
        roles = Role.objects.all()
        context = {
            'form': form,
            'roles': roles,
            'user': user
        }
        context.update(get_user_permissions(self.request.user))
        return render(request, 'authorization/edit_user.html', context)


class UserDeleteView(PermissionMixin, LoginRequiredMixin, View):
    def has_permission(self):
        return self.user_perms.get('can_manage_users', False)

    def post(self, request, pk):
        if not get_user_permissions(self.request.user).get("can_manage_users") and not self.request.user.is_superuser:
            return redirect('user_list')
        user = get_object_or_404(CustomUser, pk=pk)
        user.delete()
        return redirect('user_list')

templates/authorization/create_role.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}Create Role{% endblock %}

{% block extra_css %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block topbar %}
    {% include "partials/topbar.html" with pagetitle="Create Role" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title text-center">Create New Role</h4>
                </div>
                <div class="card-body">
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="roleName" class="form-label">Role Name</label>
                                    <input type="text" id="roleName" name="name" class="form-control"
                                           placeholder="Enter role name" required value="{{ form.name.value }}">
                                    {% for error in form.name.errors %}
                                        <div class="text-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="permissions" class="form-label">Permissions</label>
                            <div>
                                {% for permission in form.fields.permissions.queryset %}
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input"
                                               id="permission_{{ permission.pk }}" name="permissions"
                                               value="{{ permission.pk }}"
                                                {% if permission in form.instance.permissions.all %}
                                               checked {% endif %}>
                                        <label class="form-check-label"
                                               for="permission_{{ permission.pk }}">{{ permission.get_name_display }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                            {% for error in form.permissions.errors %}
                                <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="mt-3 text-right">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{% url 'role_list' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div> <!-- end card-body -->
            </div> <!-- end card -->
        </div><!-- end col -->
    </div><!-- end row -->
{% endblock content %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#permissions').select2({
                placeholder: "Select permissions",
                allowClear: true
            });
        });
    </script>
{% endblock extra_js %}

templates/authorization/edit_role.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}Edit Role{% endblock %}

{% block extra_css %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block topbar %}
    {% include "partials/topbar.html" with pagetitle="Create Role" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title text-center">Edit Role</h4>
                </div>
                <div class="card-body">
                    {% if form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="roleName" class="form-label">Role Name</label>
                                    <input type="text" id="roleName" name="name" class="form-control"
                                           placeholder="Enter role name" required value="{{ form.name.value }}">
                                    {% for error in form.name.errors %}
                                        <div class="text-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="permissions" class="form-label">Permissions</label>
                            <div>
                                {% for permission in form.fields.permissions.queryset %}
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input"
                                           id="permission_{{ permission.pk }}" name="permissions"
                                           value="{{ permission.pk }}"
                                            {% if permission in form.instance.permissions.all %}
                                           checked {% endif %}>
                                    <label class="form-check-label"
                                           for="permission_{{ permission.pk }}">{{ permission.get_name_display }}</label>
                                </div>
                            {% endfor %}
                            </div>
                            {% for error in form.permissions.errors %}
                                <div class="text-danger">{{ error }}</div>
                            {% endfor %}
                        </div>

                        <div class="mt-3 text-right">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{% url 'role_list' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div> <!-- end card-body -->
            </div> <!-- end card -->
        </div><!-- end col -->
    </div><!-- end row -->
{% endblock content %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#permissions').select2({
                placeholder: "Select permissions",
                allowClear: true
            });
        });
    </script>
{% endblock extra_js %}

templates/authorization/roles_list.html
{% extends "partials/base.html" %}

{% load static %}

{% block title %}Roles Management{% endblock %}

{% block extra_css %}
    <!-- Стили, если необходимы -->
{% endblock %}

{% block topbar %}
    {% include "partials/topbar.html" with pagetitle="Roles Management" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h4 class="card-title">Roles</h4>
                    <a href="{% url 'create_role' %}" class="btn btn-success">Add Role</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-centered mb-0" id="btn-editable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th class="text-nowrap">Role Name</th>
                                <th>Permissions</th>
                                <th>
                                    <div class="d-flex align-items-center justify-content-center gap-2">
                                        Actions
                                    </div>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for role in roles %}
                                <tr data-role-id="{{ role.id }}">
                                    <td>{{ forloop.counter0|add:start_index }}</td>
                                    <td>{{ role.name }}</td>
                                    <td>
                                        {% for permission in role.permissions.all %}
                                            {{ permission.get_name_display }}<br>
                                        {% endfor %}
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center justify-content-center gap-2">
                                            <button class="edit-role-button btn btn-primary"
                                                    data-role-id="{{ role.id }}">
                                                Edit
                                            </button>
                                            <button class="delete-role-button btn btn-danger"
                                                    data-role-id="{{ role.id }}">
                                                Delete
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    <br>
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {% if page.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.previous_page_number }}">Previous</a>
                                    </li>
                                {% endif %}
                                {% for num in page.paginator.page_range %}
                                    {% if page.number == num %}
                                        <li class="page-item active"><a class="page-link"
                                                                        href="?page={{ num }}">{{ num }}</a></li>
                                    {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
                                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.next_page_number }}">Next</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page.paginator.num_pages }}">Last
                                        &raquo;</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <!-- Table Editable plugin-->
    <script src="{% static 'libs/jquery-tabledit/jquery.tabledit.min.js' %}"></script>
    <!-- Table editable init-->
    <script src="{% static 'js/pages/role_list.init.js' %}"></script>
{% endblock %}